# Generated by Django 5.2.5 on 2025-08-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeTutorial', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_member',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
